### PR TITLE
Handle POST headers better

### LINKED ISSUE #13: Automate POST headers
User_agent = username@TestWikiAutoInactive <version>
Email = Email for the account logged into

Headers unavailable will use a default / not be added

### PR DESCRIPTION
**Pull request by RhinosF1**
resolves #13

### CODE REVIEW

**Comment by RhinosF1** [comment]
I still need to add the part where the header is modified to be the account email and make the data save to be reused but I keep hitting a timeout on the API & want lunch

**Comment by RhinosF1** [comment]
Things left to do:

- [x] Make it save the email/operator name in userinfo.cfg

- [x] Rewrite the email and warn the user to the account email if it’s different to the email given at the start.

- [x] Also, we should add something to the UA to indicate it’s a bot like BOT or SCRIPT

**Comment by RhinosF1** [comment]
Final patch incoming, also fixing a side bug with sys.argv

**Comment by RhinosF1** [comment]
Once this is merged, I will tag rc1

**Review by Reception123 — APPROVED** [review]

**Pull request merged**
